# pylint: disable=no-member

"""Update ConfluenceConfig for instance-level discovery

Revision ID: a9b8c7d6ef54
Revises: 68d0b122d51f
Create Date: 2024-05-23 11:00:00.123456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a9b8c7d6ef54'
down_revision: Union[str, Sequence[str], None] = '68d0b122d51f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('confluence_configs', sa.Column('url', sa.String(length=1023), nullable=False))
    op.add_column('confluence_configs', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('confluence_configs', sa.Column('encrypted_api_token', sa.Text(), nullable=True))
    op.add_column('confluence_configs', sa.Column('include_spaces', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('confluence_configs', sa.Column('exclude_spaces', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    
    # Create a temporary unique constraint name that is unlikely to conflict.
    # Alembic autogenerates a name, but we'll use a descriptive one here.
    op.create_unique_constraint('uq_confluence_configs_connector_id_url', 'confluence_configs', ['connector_id', 'url'])
    
    op.drop_column('confluence_configs', 'space_name')
    op.drop_column('confluence_configs', 'space_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading will fail if there is data in the new columns, as the old columns are NOT NULL.
    # This is expected for a destructive migration.
    op.add_column('confluence_configs', sa.Column('space_key', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('confluence_configs', sa.Column('space_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    
    op.drop_constraint('uq_confluence_configs_connector_id_url', 'confluence_configs', type_='unique')
    
    op.drop_column('confluence_configs', 'exclude_spaces')
    op.drop_column('confluence_configs', 'include_spaces')
    op.drop_column('confluence_configs', 'encrypted_api_token')
    op.drop_column('confluence_configs', 'email')
    op.drop_column('confluence_configs', 'url')
    # ### end Alembic commands ###