"""add producer_sync_state table

Revision ID: 68d0b122d51f
Revises: c4f3a8b7d912
Create Date: 2026-05-09 17:38:33.756913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68d0b122d51f'
down_revision: Union[str, Sequence[str], None] = 'c4f3a8b7d912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producer_sync_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=500), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producer_sync_state')),
    sa.UniqueConstraint('source', 'resource_id', name='uq_producer_sync_state_source_resource')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producer_sync_state')
    # ### end Alembic commands ###
