"""add command_status table

Revision ID: 44e8b55d5de9
Revises: a9b8c7d6ef54
Create Date: 2026-07-30 13:59:34.237728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '44e8b55d5de9'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6ef54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('command_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Uuid(), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_status'))
    )
    op.create_index(op.f('ix_command_status_command_id'), 'command_status', ['command_id'], unique=True)
    op.drop_constraint(op.f('uq_confluence_configs_connector_id_url'), 'confluence_configs', type_='unique')
    op.create_unique_constraint(op.f('uq_confluence_configs_connector_id'), 'confluence_configs', ['connector_id', 'url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_confluence_configs_connector_id'), 'confluence_configs', type_='unique')
    op.create_unique_constraint(op.f('uq_confluence_configs_connector_id_url'), 'confluence_configs', ['connector_id', 'url'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_command_status_command_id'), table_name='command_status')
    op.drop_table('command_status')
    # ### end Alembic commands ###
