CONNECTOR_REGISTRY = {
    "github": {
        "display_name": "GitHub",
        "icon": "fa-brands fa-github",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "jira": {
        "display_name": "Jira",
        "icon": "fa-brands fa-jira",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "slack": {
        "display_name": "Slack",
        "icon": "fa-brands fa-slack",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "teams": {
        "display_name": "Microsoft Teams",
        "icon": "fa-brands fa-microsoft",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "confluence": {
        "display_name": "Confluence",
        "icon": "fa-brands fa-confluence",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "google_docs": {
        "display_name": "Google Docs",
        "icon": "fa-brands fa-google",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "sharepoint": {
        "display_name": "SharePoint",
        "icon": "fa-brands fa-microsoft",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "email": {
        "display_name": "Email",
        "icon": "fa-solid fa-envelope",
        "section": "connections",
        "supports_items": True,
        "setup_type": "db_backed",
    },
    "atlassian_mcp": {
        "display_name": "Atlassian MCP Server",
        "icon": "fa-brands fa-atlassian",
        "section": "mcp",
        "supports_items": False,
        "setup_type": "db_backed",
    },
    "github_mcp": {
        "display_name": "GitHub MCP Server",
        "icon": "fa-brands fa-github",
        "section": "mcp",
        "supports_items": False,
        "setup_type": "manual",
    },
}
